### ISSUE TITLE
Import trace for requested module | webpack

### ISSUE THREAD

**Issue by ahmedrowaihi** [flydrive-js/core#1]
I keep getting this error in console
I am in a monorepo using PNPM & Turbo
```
 ⚠ ../../node_modules/.pnpm/@poppinss+utils@6.7.3/node_modules/@poppinss/utils/build/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/.pnpm/@poppinss+utils@6.7.3/node_modules/@poppinss/utils/build/index.js
../../node_modules/.pnpm/flydrive@1.0.2_@aws-sdk+client-s3@3.600.0_@aws-sdk+s3-request-presigner@3.600.0/node_modules/flydrive/build/chunk-XTE5URPJ.js
../../node_modules/.pnpm/flydrive@1.0.2_@aws-sdk+client-s3@3.600.0_@aws-sdk+s3-request-presigner@3.600.0/node_modules/flydrive/build/drivers/s3/main.js
```

**Comment by RomainLanz** [comment]
Hey @ahmedrowaihi! 👋🏻 

We need more information to help you.
The best would be to have a repository with **the minimum amount of code** to reproduce your issue.

**Comment by RomainLanz** [comment]
I had no issue locally but I have:

- Remove the custom endpoint (since I don't have any)
- Added the region to the `.env` file
- Remove the URL generation, since it is not needed too

**Comment by RomainLanz** [comment]
Alright, gotcha.

The code works fine; the issue is the log sent to the console.
I am not sure where that comes from, it is probably Turbo.

**Comment by RomainLanz** [comment]
I will also check on my side to see if anything come to my mind.

Good luck with your exams! 🙌🏻

**Comment by andresgutgon** [comment]
Just starting trying flydrive this weekend. Same error in NextJS + PNPM + Turborepo

**Comment by andresgutgon** [comment]
Could be this https://github.com/poppinss/utils/blob/develop/src/import_default.ts#L19 ?

I'm reading that Webpack  can't require dynamically https://stackoverflow.com/a/59235546

I've no idea tbh. Please don't get confused for my guess

**Comment by RomainLanz** [comment]
It is a known issue of Webpack. @Julien-R44 [already made some investigation in Bentocache](https://github.com/Julien-R44/bentocache/issues/16#issuecomment-2051997448) for the same issue.

**Comment by andresgutgon** [comment]
Uhmm, would be the long term solution here? 

I understand @poppings do that to have sub-set of lodash functionality no?

**Comment by andresgutgon** [comment]
> best solution is that we may reallocate the export of fsImportAll and importDefault to their own path, ( not in index )
so only libs that need them, can import them through @poppings/utils/import-helpers

Yes, this would be ideal

**Comment by andresgutgon** [comment]
> maybe we can extend exports from package.json instead :'D

How would that work? How updating other AdonisJS packages being updated can be avoided?

**Comment by andresgutgon** [comment]
But consumers of this package still needs to be updated no?

**Comment by andresgutgon** [comment]
Ahh I got it 👌  Great. Can you do the PR?

**Comment by thetutlage** [comment]
Can I understand the root of the problem? Why does TurboPack complains about a function that performs a dynamic import or a filesystem read operation?

Sorry, I am not aware of Turbopack or internal workings of Next.js, so I am trying to understand what is the root of the warning.

**Comment by thetutlage** [comment]
Okay. In that case, I am not sure if FlyDrive is meant to be used with WebPack or any bundler for that matter.

I don't want to discourage the usage of FlyDrive, but if we end up in a cycle where we have to optimize/re-structure code to make FlyDrive work with a bundler, then I might not be eager to do so. Simply, because I want to keep my projects simple and easy to maintain for the longer run.

Now, regarding this simple change of `@poppinss/utils`, I will go ahead and provide a fix for it and see if everything goes smoothly beyond that. 👍

**Comment by thetutlage** [comment]
Yeah. I think we will go with the submodules approach (as you suggested) in `@poppinss/utils`.

**Comment by ahmedrowaihi** [comment]
Should we close this ?:)

**Comment by andresgutgon** [comment]
Is poppins version bumped in this project with the fix?

**Comment by ahmedrowaihi** [comment]
not yet, it's 10 versions behind

**Comment by RomainLanz** [comment]
> not yet, it's 10 versions behind

There's no need to update the package in this repository. The current release of `@poppinss/utils` already complies with our semver range.

With the `^6.7.3` version specifier, npm will automatically install the latest compatible version (`6.8.3`).

**Comment by thetutlage** [comment]
Its not 10 versions behind and as Romain said, it's within the same semver hence the latest version will be installed automatically

**Comment by andresgutgon** [comment]
Thanks a lot for the fix! I'll try what you said

**Comment by ahmedrowaihi** [comment]
confirmed 
<img width="683" alt="image" src="https://github.com/user-attachments/assets/3300eab5-d734-4ed2-bc91-db6e20809e82">
thank you!
