### ISSUE TITLE
Shouldn't the S3 driver be compatible with supabase storage

### ISSUE THREAD

**Issue by Fawwaz-2009** [flydrive-js/core#4]
hey there 👋 ,

From what I understand the S3 driver is not meant to be only used for AWS S3 but any compatible storage that implement S3. Supabase recently have added support to S3, and I tried to use the S3 drive in my adonis project and supabase storage but I got this error that looks like it came from aws?

if this is indeed not the expected behaviour, I'll be happy to create a reproduction of the issue. For now here is the error I'm seeing.
```
"Cannot write file at location \"uploads/kf1z592ns20206nnxsuebchx.jpg\": The AWS Access Key Id you provided does not exist in our records."
```

**Comment by thetutlage** [comment]
Hey!

Yes, the S3 driver can be used with any compatible S3 service. We are already using it for R2 and Digital Ocean spaces as long as that service supports all the operations executed by FlyDrive.

In this case, it looks like, the error seems to be coming directly from Supabase during authentication. So yes it will be nice to once check if you can use the AWS SDK directly and connect to supabase from there or not

**Comment by Fawwaz-2009** [comment]
Hey @thetutlage thanks so much for the quick reply :)

so when I try the ace command to the driver (`node ace add @adonisjs/drive`) I would expect there would be one S3 option but there are 3. one for S3 AWS, Digital ocean spaces and cloudflare R2
![image](https://github.com/user-attachments/assets/c325ac81-5956-4b88-92d9-6fec507986dc)

Also I'll admit I'm not an expert at S3 but I dont' see how these input/configs, would be sufficient to tell if you suppose to look for the S3 bucket at AWS or supabase
![image](https://github.com/user-attachments/assets/bb04a66c-00d7-48c5-ab6c-5d410d562708)

Also seems that the cloudflare R2 ask for very different configs
![image](https://github.com/user-attachments/assets/975a8cf9-fe02-4f33-a75b-96d7835f344e)

**Comment by Fawwaz-2009** [comment]
ok quick updates, for some reason just passing the exact values to the R2 setup has worked with supabase !, the big difference was the `R2_endpoint` which was not present in the AWS version

**Comment by thetutlage** [comment]
You might have to read a bit about how all these providers use S3 SDK and yes the endpoint is the biggest factor here, which isn't needed with AWS S3 storage, because the endpoint is used by their SDK.

Regarding different environment variables. They are needed, since one project might be using both R2 and S3, or S3 and Digital ocean spaces and you wouldn't want to share the credentials across these services.

**Comment by thetutlage** [comment]
I will close the issue for now. Feel free to create a discussion thread if you have more questions :)

**Comment by Fawwaz-2009** [comment]
thanks @thetutlage :)
