### ISSUE TITLE
Shouldn't use cdnUrl with getSignedUrl using S3?

### ISSUE THREAD

**Issue by hieuhuynh93** [flydrive-js/core#5]
As the title, although I set cdnUrl (using CloudFront) on config, the URL is AWS S3 URL. 
How I can use cdnUrl on getSignedUrl?

**Comment by thetutlage** [comment]
The signed URLs are used to serve private files for a limited time. I don't think you want to serve them via a CDN (that usually have global cache as well). 

Feel free to point me to the AWS docs where they allow a CDN to serve private files and then I may look into support it.

**Comment by hieuhuynh93** [comment]
@thetutlage Previously I used this package along with the AdonisJS v5 Drive package to generate a signed URL using CloudFront URL since aws-sdk doesn't support this. 
https://www.npmjs.com/package/aws-cloudfront-sign

Is it possible to implement a similar feature in this package?
If not I will use the above solution for my current project.

**Comment by thetutlage** [comment]
You can self assign a custom URL builder within the config and use this package under the hood.  Here are the relevant docs. https://flydrive.dev/docs/services/s3#creating-signed-urls

**Comment by hieuhuynh93** [comment]
I used it but it returned the S3 URL instead of CloudFront URL. I already set cdnUrl to CloudFront URL.

**Comment by thetutlage** [comment]
Can you share how you setup the `urlBuilder`?

**Comment by hieuhuynh93** [comment]
Sure. I'm using Drive in AdonisJS V6, here is my code:
Here is `config/drive.ts`
```typescript
services: {
    s3: services.s3({
      credentials: {
        accessKeyId: env.get('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env.get('AWS_SECRET_ACCESS_KEY'),
      },
      region: env.get('AWS_REGION'),
      bucket: env.get('S3_BUCKET'),
      visibility: 'private',
      cdnUrl: env.get('S3_CDN_URL'),
    }),
  },
```

S3_CDN_URL's value is `https://xxx.cloudfront.net`

Get image function
```typescript
export const retrieve = async (path: string, isSigned: boolean = false) => {
  const imagePath = path || 'assets/image-placeholder.svg'
  const disk = drive.use()
  if (isSigned) {
    return disk.getSignedUrl(imagePath, {
      expiresIn: '30mins',
    }) // This will return https://bucket-name.s3.ap-southeast-1.amazonaws.com/aaa.png
  }

  return disk.getUrl(imagePath) // This will return https://xxx.cloudfront.net/aaa.png
}
```

**Comment by thetutlage** [comment]
You are not using the urlBuilder to define custom logic, instead you are using the `cdnUrl` property.

If you look at this example in the link I shared with you, there will be an option `generateSignedURL` to self generate a signed URL.

![CleanShot 2024-10-16 at 19 41 08@2x](https://github.com/user-attachments/assets/24880cdc-350a-4da4-8e2e-339963159b4e)
